# Generated by Django 3.2 on 2023-03-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
